### PR TITLE
Chef fixes

### PR DESCRIPTION
**Pull request by dswebbthg**
Fixed an issue with the readme, and the libraries/clihelper that cause issues during chef runs ala:

    NoMethodError
    -------------
    undefined method `shellescape' for "ip":String
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/pacemaker/libraries/clihelper.rb:57:in `block in format_param_hash'
    /var/chef/cache/cookbooks/pacemaker/libraries/clihelper.rb:56:in `each'
    /var/chef/cache/cookbooks/pacemaker/libraries/clihelper.rb:56:in `format_param_hash'
    /var/chef/cache/cookbooks/pacemaker/providers/primitive.rb:45:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/pacemaker/providers/primitive.rb:43:in `block in class_from_file'

### CODE REVIEW

**Comment by joerocklin** [comment]
Would love to see this get merged, I'm working on integrating this into a cookbook managing HAProxy instances and need the fix to manage IPs.

**Comment by jmccann** [comment]
I'll try to take a look at this today.  We didn't run into this issue so need to investigate.

Sorry for the delay in response.  The primary on this is on vacation!!

**Comment by dswebbthg** [comment]
if it helps at all this was being run on a CentOS 7.2 box with the following ruby / chef setup:

ruby-2.0.0.598-25.el7_1.x86_64
chef-12.5.1-1.el7.x86_64

**Comment by jmccann** [comment]
I think I got this figured out with #7.  I'm in favor of #7 as it keeps the code as is and just includes loading the `shellwords` library.

**Comment by jmccann** [comment]
@dswebbthg @joerocklin Fixed in `1.0.1` that was just released.

**Pull request closed without merging**
